nuts_and_bolts/products/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField

class ProductForm(FlaskForm):
    quantity = SelectField('Quantity', validate_choice=False)
    add = SubmitField('Add to cart')
    

nuts_and_bolts/receipts/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField
from wtforms.validators import DataRequired


class FindOrdersForm(FlaskForm):
    email = StringField('Email address', validators=[DataRequired()])
    search = SubmitField('Search')

nuts_and_bolts/cart/routes.py
from datetime import datetime
from decimal import Decimal
from flask import Blueprint, render_template, session, url_for, flash, redirect, abort
from flask_mail import Message
from nuts_and_bolts.config import Config
from nuts_and_bolts.cart.forms import CartForm
from nuts_and_bolts import db, mail
from nuts_and_bolts.models import Product, User, Receipt, ReceiptProducts

cart = Blueprint('cart', __name__)


@cart.route('/cart', methods=['GET', 'POST'])
def show_cart():
    form = CartForm()
    if form.validate_on_submit():
        if form.checkout.data:
            products = db.session.query(Product).filter(
                Product.id.in_(session['cart'])).all()
            understocked_products = []
            for product in products:
                if session['cart'][str(product.id)] > product.quantity:
                    session['cart'][str(product.id)] = product.quantity
                    understocked_products.append(product.name)
            if understocked_products:
                flash('The following products are in limited supply: '
                      + ', '.join(understocked_products) +
                      '. The quantities in your cart have been adjusted.',
                      'danger')
                return redirect(url_for('cart.show_cart'))
            if form.email.data:
                customer = User.query.filter_by(email=form.email.data).first()
                if not customer:
                    new_customer = User(
                        email=form.email.data
                    )
                    customer = new_customer
                session['email'] = customer.email
                total_cost = 0
                for product in products:
                    total_cost += (Decimal(product.price) *
                                   Decimal(session['cart'][str(product.id)]))
                new_receipt = Receipt(
                    user=customer,
                    total_cost=str(total_cost),
                    datetime=datetime.utcnow()
                )
                items = ''''''
                for product in products:
                    product.quantity -= session['cart'][str(product.id)]
                    new_receipt_product = ReceiptProducts(
                        product=product,
                        price=product.price,
                        quantity=session['cart'][str(product.id)],
                        receipt=new_receipt
                    )
                    db.session.add(new_receipt_product)
                    db.session.commit()
                    items += f'''{new_receipt_product.product.name}
    {new_receipt_product.price} each, Quantity: {new_receipt_product.quantity}
'''
                    session['cart'].pop(str(product.id))
                db.session.add(new_receipt)
                db.session.commit()
                msg = Message('Nuts and Bolts Transaction ID: ' + str(new_receipt.id),
                              sender=Config.MAIL_USERNAME,
                              recipients=[customer.email])
                msg.body = f'''Transaction ID #{str(new_receipt.id)} was successful!

    {items}
The total cost was: ${str(new_receipt.total_cost)}

Thank you for shopping with us!
- Nuts and Bolts Staff
'''
                mail.send(msg)
                flash('Thank you for shopping with Nuts & Bolts!'
                      + 'Your receipt was sent to your Email address',
                      'success')
                return redirect(url_for('products.product_list'))
            else:
                flash('Please enter an email address to checkout.', 'warning')
                return redirect(url_for('cart.show_cart'))
    _cart = {}
    if session['cart']:
        products = db.session.query(Product).filter(
            Product.id.in_(session['cart']))
        for product in products:
            _cart[str(product.id)] = {
                "name": product.name,
                "price": product.price,
                "sku": product.sku,
                "quantity": session['cart'][str(product.id)]
            }
    return render_template('show_cart.html', cart=_cart, form=form)


@cart.route('/cart/clear')
def clear_cart():
    if 'cart' in session:
        session['cart'] = {}
        flash('Your cart has been cleared.', 'success')
    return redirect(url_for('cart.show_cart'))


@cart.route('/cart/remove_item/<_id>')
def remove_item(_id):
    if _id in session['cart']:
        session['cart'].pop(_id, None)
        product = db.session.query(Product).filter_by(id=_id).first()
        flash(product.name + 'has been removed from cart!', 'success')
        return redirect(url_for('cart.show_cart'))
    else:
        return abort(404)

nuts_and_bolts/main/routes.py
from flask import Blueprint, render_template, redirect, flash, request, url_for
from flask_mail import Message
from flask_login import login_required
from nuts_and_bolts.shared.utils import admin_required
from nuts_and_bolts.config import Config
from nuts_and_bolts import db, mail
from nuts_and_bolts.models import Product, Testimonial
from nuts_and_bolts.main.forms import QuestionsForm, TestimonialForm

main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('home.html')


@main.route('/contact_us', methods=['GET', 'POST'])
def contact_us():
    form = QuestionsForm()
    if form.validate_on_submit():
        msg = Message('Question about ' + form.subject.data + ' Sent',
                      sender=Config.MAIL_USERNAME,
                      recipients=[form.email.data],
                      bcc=[Config.MAIL_USERNAME])
        msg.body = f''' Your question about {form.subject.data} has been sent to our staff!
Your question was:

{form.text.data}

We will reach out in a few days after review.    
Thank you.

- Nuts and Bolts Staff
'''
        mail.send(msg)
        flash('Question submitted! Check email for confirmation.', 'success')
        return redirect(url_for('main.contact_us'))
    return render_template('contact_us.html', form=form)


@main.route('/about_us')
def about_us():
    return render_template('about_us.html')


@main.route('/faq')
def faq():
    return render_template('faq.html')


@main.route('/search', methods=['GET', 'POST'])
def search():
    products = []
    _search = request.form['search']
    if _search:
        products = db.session.query(Product).filter(
            Product.name.contains(_search))
    return render_template('search.html', search=_search, products=products)


@main.route('/testimonials', methods=['GET', 'POST'])
def testimonials():
    testimonial_list = db.session.query(Testimonial).order_by(Testimonial.name)
    form = TestimonialForm()
    if form.validate_on_submit():
        new_testimonial = Testimonial(
            name=form.name.data,
            text=form.text.data
        )
        db.session.add(new_testimonial)
        db.session.commit()
        flash(
            f'Thank you for your testimonial, {form.name.data}. It has been submitted for review!',
            'success'
        )
        return redirect(url_for('main.testimonials'))
    form.submit.label.text = 'Add Testimonial'
    return render_template('testimonials.html', form=form, testimonial_list=testimonial_list)


@main.route('/testimonial/<int:testimonial_id>/toggle_visibility')
@login_required
@admin_required
def toggle_testimonial_visibility(testimonial_id):
    testimonial = db.session.query(
        Testimonial).filter_by(id=testimonial_id).first()
    testimonial.visibility = not testimonial.visibility
    db.session.commit()
    return redirect(url_for('main.testimonials'))

nuts_and_bolts/management/routes.py
import os
from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app
from flask_login import login_required
from nuts_and_bolts.management.forms import InventoryForm
from nuts_and_bolts.models import Product
from nuts_and_bolts import db
from nuts_and_bolts.shared.utils import admin_required
from nuts_and_bolts.management.utils import save_image

management = Blueprint('management', __name__)


@management.route('/management/add_to_inventory', methods=['GET', 'POST'])
@login_required
@admin_required
def add_to_inventory():
    form = InventoryForm()
    form.image_file.label.text = 'Add Product Image'
    if form.validate_on_submit():
        image_filename = None
        if form.image_file.data:
            image_filename = save_image(form.image_file.data)
        new_product = Product(
            name=form.name.data,
            description=form.description.data,
            price=form.price.data,
            sku=int(form.sku.data),
            quantity=int(form.quantity.data),
            image_name=image_filename,
            image_alt_text=form.image_alt_text.data
        )
        db.session.add(new_product)
        db.session.commit()
        flash(f'Entry created for {form.name.data}!', 'success')
        return redirect(url_for('products.product_list'))
    form.submit.label.text = 'Add'
    return render_template('add_to_inventory.html', form=form)


@management.route('/management/update_inventory/<int:product_id>',  methods=['GET', 'POST'])
@login_required
@admin_required
def update_inventory(product_id):
    product = Product.query.get_or_404(product_id)
    form = InventoryForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.image_file.data:
                os.remove(
                    os.path.join(
                        current_app.root_path,
                        'static/images/products',
                        product.image_name
                    )
                )
                product.image_name = save_image(form.image_file.data)
            product.image_alt_text = form.image_alt_text.data
            product.name = form.name.data
            product.description = form.description.data
            product.price = form.price.data
            product.sku = int(form.sku.data)
            product.quantity = int(form.quantity.data)
            db.session.commit()
            flash('Entry updated for ' + form.name.data + '!', 'success')
            return redirect(url_for('products.product_list'))
        else:
            return render_template('update_inventory.html', form=form)
    form.id.data = product.id
    form.image_alt_text.data = product.image_alt_text
    form.name.data = product.name
    form.description.data = product.description
    form.price.data = product.price
    form.sku.data = product.sku
    form.quantity.data = int(product.quantity)
    form.submit.label.text = 'Update'
    return render_template('update_inventory.html', form=form)

nuts_and_bolts/products/routes.py
from flask import Blueprint, redirect, url_for, render_template, abort, session, flash
from nuts_and_bolts.models import Product
from nuts_and_bolts.products.forms import ProductForm
from nuts_and_bolts import db

products = Blueprint('products', __name__)


@products.route('/products/all')
def product_list():
    _products = db.session.query(Product).order_by(Product.sku)
    return render_template('product_list.html', products=_products)


@products.route('/product/<product_sku>', methods=['GET', 'POST'])
def product_page(product_sku):
    product = Product.query.filter_by(sku=product_sku).first()
    if product:
        form = ProductForm()
        if form.validate_on_submit():
            session['cart'][str(product.id)] = int(form.quantity.data)
            flash(product.name + ' added to cart!', 'success')
            return redirect(url_for('cart.show_cart'))
        form.quantity.choices = [(i, i)
                                 for i in range(product.quantity + 1)][1:]
        if str(product.id) in session['cart']:
            form.quantity.data = str(session['cart'][str(product.id)])
            form.add.label.text = 'Update'
        return render_template('product.html', product=product, form=form)
    return abort(404)

nuts_and_bolts/receipts/routes.py
from flask import Blueprint, render_template, flash
from flask_login import current_user
from nuts_and_bolts.receipts.forms import FindOrdersForm
from nuts_and_bolts.models import User, Receipt

receipts = Blueprint('receipts', __name__)


@receipts.route('/receipts', methods=['GET', 'POST'])
def all_receipts():
    _receipts = []
    form = FindOrdersForm()
    if current_user.is_authenticated:
        _receipts = sorted(current_user.receipts, key=lambda i: i.datetime, reverse=True)
        if not _receipts:
            flash("You don't have any receipts.", 'danger')
    if form.validate_on_submit():
        customer = User.query.filter_by(email=form.email.data).first()
        if customer:
            _receipts = sorted(customer.receipts, key=lambda i: i.datetime, reverse=True)
        if not _receipts:
            flash('No receipts match that email address.', 'danger')
    return render_template('receipts.html', receipts=_receipts, form=form)


@receipts.route('/receipt/<int:receipt_id>', methods=['GET', 'POST'])
def receipt(receipt_id):
    _receipt = Receipt.query.get_or_404(receipt_id)
    return render_template('receipt.html', receipt=_receipt)

nuts_and_bolts/templates/home.html
{% extends 'layout.html' %}
{% block content %}

<div class="text-center">
  <div class="banner-home1">
    <h1 class="my-5">Nuts & Bolts</h1>
  </div>
  <div class="banner-home2 my-3">
    <h2 class="my-3">All the Essentials for your next home improvement project</h2>
    <img class="rounded" src="{{ url_for('static', filename = 'images/Carpenter-Photo.jpg') }}" alt="A man cutting a board">
    <h2 class="mt-2 mb-5">Design your Dreams</h2>
  </div>
  <div class="container-fluid my-3 text-center">
    <img class="img-thumbnail" src="{{ url_for('static', filename = 'images/brands.jpg') }}" alt="Various logos of brands available">
    <h3>Brands you can Trust</h3>
  </div>
</div>

{% endblock content %}

nuts_and_bolts/templates/layout.html
<!DOCTYPE html>
<html lang=en>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{{ url_for('static', filename = 'logos/favicon.ico') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/main.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/sticky-footer-navbar.css') }}">
  <link href="https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" rel="stylesheet">
  <title>Nuts & Bolts</title>
</head>

<body>
  <header class="site-header nav-font">
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">
          <img src="{{ url_for('static', filename = 'logos/logo.png') }}" class="d-inline-block align-middle"
            style="height: 40px;width: auto;" alt="Nuts and Bolts logo">
          <span class="ml-1 align-bottom">Nuts & Bolts</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <!-- Links for the middle of the nav bar inside this div -->
          <hr>
          <div class="navbar-nav ml-auto">
            <form method="POST" action="{{ url_for('main.search') }}">
              <input type="text" placeholder="Search..." name="search">
              <input type="submit" value="Search" class="btn-sm btn-primary">
            </form>
          </div>
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{{ url_for('products.product_list') }}">Product List</a>
          </div>
          <!-- Links for the right side of the nav bar inside this div -->
          <hr class="bg-dark">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{{ url_for('cart.show_cart') }}">Cart</a>
            <a class="nav-item nav-link" href="{{ url_for('receipts.all_receipts') }}">Receipts</a>
          </div>
          {%- if current_user.is_authenticated and current_user.is_admin -%}
          <hr>
          <div class="navbar-nav ml-auto">
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkManageInventory"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Manage Inventory
              </a>
              <div class="dropdown-menu bg-dark navbar-dark" aria-labelledby="navbarDropdownMenuLinkManageInventory">
                <a class="dropdown-item nav-link" href="{{ url_for('management.add_to_inventory') }}">Add Inventory</a>
              </div>
            </div>
          </div>
          {%- endif -%}
          <div class="d-lg-none">
            <div class="spacer-2"></div>
            <div class="spacer-2"></div>
            <div class="navbar-nav">
              <a href="{{ url_for('main.contact_us') }}" class="nav-item nav-link">Contact Us</a>
              <a href="{{ url_for('main.about_us') }}"  class="nav-item nav-link">About Us</a>
              <a href="{{ url_for('main.faq') }}" class="nav-item nav-link">FAQ</a>
              <a href="{{ url_for('main.testimonials') }}" class="nav-item nav-link">Testimonials</a>
            </div>
            <hr>
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a href="{{ url_for('auth.logout') }}" class="nav-item nav-link">Logout</a>
              {% else %}
              <a href="{{ url_for('auth.login') }}" class="nav-item nav-link">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="w-100 mx-15px">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="text-center alert alert-{{ category }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </main>
  <footer class="footer bg-dark d-none d-lg-block">
    <div class="container nav-font text-center" id="footer">
      <a class="mx-4" href="{{ url_for('main.contact_us') }}">Contact Us</a>
      <a class="mx-4" href="{{ url_for('main.about_us') }}">About Us</a>
      <a class="mx-4" href="{{ url_for('main.faq') }}">FAQ</a>
      <a class="mx-4" href="{{ url_for('main.testimonials') }}">Testimonials</a>
      {%- if current_user.is_authenticated -%}
      <a href="{{ url_for('auth.logout') }}" class="mx-4">Logout</a>
      {%- else -%}
      <a href="{{ url_for('auth.login') }}" class="mx-4">Login</a>
      {%- endif -%}
    </div>
  </footer>
  <script type="text/javascript" src="{{ url_for('static', filename = 'js/jquery-3.2.1.slim.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename = 'js/bootstrap.bundle.min.js') }}"></script>
</body>

</html>

nuts_and_bolts/templates/product.html
{% extends 'layout.html' %}
{% block content %}
<article class="media rounded content-section my-2">
    <div class="media-body">
        <div class="article-metadata no-overflow">
            {% if product.image_name %}
            <div class="text-center mw-100">
                <img class="border border-secondary mw-100"
                    src="{{ url_for('static', filename='images/products/' + product.image_name ) }}"
                    {% if product.image_alt_text %} alt="{{ product.image_alt_text }}" {% endif %}>
            </div>
            {% endif %}
            <span class="font-weight-bold">${{ product.price }}</span>
            <span class="font-weight-bold float-right">SKU: {{ product.sku }}</span>
        </div>
        <h2 class="article-title">{{ product.name | title }}</h2>
        <p class="article-content text-wrap-word-break">{{ product.description }}</p>
        <div>
            {%- if current_user.is_authenticated and current_user.is_admin -%}
            <a class="btn btn-secondary mt-2"
                href="{{ url_for('management.update_inventory', product_id=product.id) }}">Update</a>
            {%- endif -%}
            {%- if product.quantity == 0 -%}
            <b class="text-danger"> OUT OF STOCK!</b>
            {%- else -%}
            <div class="col-md-2 ml-auto">
                <form action="" method="POST">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.quantity.label(class="form-control-label") }}
                        {% if form.quantity.errors %}
                        {{ form.quantity(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.quantity.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.quantity(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.add(class="btn btn-outline-dark w-100") }}
                    </div>
                </form>
            </div>
            {%- endif -%}
        </div>
    </div>
</article>
{% endblock content %}

nuts_and_bolts/templates/product_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="my-5">
    <h1 class="text-center">Available Products</h1>
</div>
{% if products %}
{% for product in products %}
<a href="{{ url_for('products.product_page', product_sku=product.sku) }}" class="text-decoration-none text-dark">
    <article class="media rounded content-section my-2">
        <div class="media-body">
            <div class="article-metadata no-overflow">
                <span class="font-weight-bold">${{ product.price }}</span>
                <span class="font-weight-bold float-right">SKU: {{ product.sku }}</span>
            </div>
            <h2 class="article-title">{{ product.name | title }}</h2>
            <p class="article-content text-wrap-word-break">{{ product.description }}</p>
            <div>
                {%- if product.quantity == 0 -%}
                <b class="text-danger"> OUT OF STOCK!</b>
                {%- endif -%}
            </div>
        </div>
    </article>
</a>
{% endfor %}
{% else %}
<h2 class="text-center">Uh-oh, it looks like there aren't any products to display.</h2>
{% endif %}
{% endblock content %}

nuts_and_bolts/templates/receipts.html
{% extends "layout.html" %}
{% block content %}
{% if receipts %}
{% for receipt in receipts %}
<a class="text-decoration-none" href="{{ url_for('receipts.receipt', receipt_id=receipt.id) }}">
    <article class="media rounded content-section my-2">
        <div class="media-body">
            <div class="article-metadata no-overflow">
                <span class="font-weight-bold">Date ordered: {{ receipt.datetime.strftime('%m/%d/%Y') }}</span>
            </div>    
            <span class="font-weight-bold">{{ receipt.receipt_products | count }} products</span>
            <span class="font-weight-bold float-right">Total: ${{ receipt.total_cost }}</span>
        </div>
    </article>
</a>
{% endfor %}
{% else %}
<div class="content-section col-md-8 mx-auto">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Find my previous orders</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.search(class="btn btn-outline-dark w-100") }}
        </div>
    </form>
</div>
{% endif %}
{% endblock content %}

nuts_and_bolts/templates/search.html
{% extends 'layout.html' %}
{% block content %}
<div class="my-5">
    <h1 class="text-center">Search Results</h1>
</div>
{% if products %}
{% for product in products %}
<a href="{{ url_for('products.product_page', product_sku=product.sku) }}" class="text-decoration-none text-dark">
    <article class="media rounded content-section my-2">
        <div class="media-body">
            <div class="article-metadata no-overflow">
                <span class="font-weight-bold">${{ product.price }}</span>
                <span class="font-weight-bold float-right">SKU: {{ product.sku }}</span>
            </div>
            <h2 class="article-title">{{ product.name | title }}</h2>
            <p class="article-content text-wrap-word-break">{{ product.description }}</p>
            <div>
                {%- if product.quantity == 0 -%}
                <b class="text-danger"> OUT OF STOCK!</b>
                {%- endif -%}
            </div>
        </div>
    </article>
</a>
{% endfor %}
{% else %}
<h2 class="text-center">Uh-oh, it looks like there aren't any results.</h2>
{% endif %}
{% endblock content %}

nuts_and_bolts/templates/show_cart.html
{% extends 'layout.html' %}
{% block content %}
<div class="my-5">
    <h1 class="text-center">Cart</h1>
</div>
{% if cart %}
{% for key in cart %}
<article class="media rounded content-section my-2">
    <div class="media-body">
        <div class="article-metadata no-overflow">
            <span class="font-weight-bold">${{ cart[key]['price'] }}</span>
            <span class="font-weight-bold float-right">SKU: {{ cart[key]['sku'] }}</span>
        </div>
        <h2 class="article-title">{{ cart[key]['name'] | title }}</h2>
        <p class="font-weight-bold float-right">Quantity: {{ cart[key]['quantity'] }}</p>
        <a class="btn btn-outline-danger" href="{{ url_for('cart.remove_item', _id=key) }}">Remove Item</a>
    </div>
</article>
{% endfor %}
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="mt-2">
        {% if current_user.is_authenticated %}
        <div class="d-none">
            {{ form.email(value=current_user.email) }}
        </div>
        {% else %}
        <div class="form-group col-md-6 ml-auto">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        {% endif %}
        <a href="{{ url_for('cart.clear_cart') }}" class="btn btn-outline-danger">Clear Cart</a>
        {{ form.checkout(class="btn btn-secondary float-right") }}
    </div>
</form>
{% else %}
<h2 class="text-center">Uh-oh, it looks like the cart is empty.</h2>
{% endif %}
{% endblock content %}

nuts_and_bolts/templates/testimonials.html
{% extends "layout.html" %}
{% block content %}
<div class="my-5">
    <h1 class="text-center">Customer Testimonials</h1>
</div>
{% for testimonial in testimonial_list %}
{% if testimonial.visibility %}
<article class="media rounded content-section my-2">
    <div class="media-body">
        <h2 class="article-title">{{ testimonial.name | title }}</h2>
        <p class="article-content text-wrap-word-break">{{ testimonial.text }}</p>
        {% if current_user.is_admin %}
        <div>
            <a href="{{ url_for('main.toggle_testimonial_visibility', testimonial_id=testimonial.id) }}"
                class="btn btn-danger">Make Hidden</a>
        </div>
        {% endif %}
    </div>
</article>
{% endif %}
{% endfor %}
<div class="content-section col-md-8 center my-5">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">{{ form.name.label(class="form-control-label")}}
                {% if form.name.errors %}
                {{ form.name(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">{{ form.text.label(class="form-control-label")}}
                {% if form.text.errors %}
                {{ form.text(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.text.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.text(class="form-control form-control-lg", rows="5") }}
                {% endif %}
            </div>
            <div class="text-center">{{ form.submit }}</div>
        </fieldset>
    </form>
</div>

{% for testimonial in testimonial_list %}
{% if current_user.is_admin and not testimonial.visibility %}
<article class="media rounded content-section my-2">
    <div class="media-body">
        <h2 class="article-title">{{ testimonial.name | title }}</h2>
        <p class="article-content text-wrap-word-break">{{ testimonial.text }}</p>
        {% if current_user.is_admin %}
        <div>
            <a href="{{ url_for('main.toggle_testimonial_visibility', testimonial_id=testimonial.id) }}"
                class="btn btn-success">Make Visible</a>
        </div>
        {% endif %}
    </div>
</article>
{% endif %}
{% endfor %}

{% endblock content %}